apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: chatconnectionircs.eevee.bot
spec:
  group: eevee.bot
  names:
    kind: chatconnectionirc
    plural: chatconnectionircs
    singular: chatconnectionirc
    shortNames:
      - chatconnectionirc
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: chatconnectionircSpec defines the desired state of
                chatconnectionirc
              properties:
                ipcConfig:
                  type: string
                  description: IPC configuration name
                image:
                  type: string
                  description: Image name and tag for the IRC connection instance
                connections:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Display name for this network
                      enabled:
                        type: boolean
                        description: Enable this connection
                      irc:
                        type: object
                        properties:
                          host:
                            type: string
                            description: Host to connect to
                          port:
                            type: number
                            description: Port
                          ssl:
                            type: boolean
                            description: SSL
                          autoReconnect:
                            type: boolean
                            description: Auto reconnect
                          autoReconnectWait:
                            type: number
                            description: Auto reconnect wait time in milliseconds
                          autoReconnectMaxRetries:
                            type: number
                            description: Auto reconnect max retries
                          autoRejoin:
                            type: boolean
                            description: Auto rejoin channels
                          autoRejoinWait:
                            type: number
                            description: Auto rejoin wait time in milliseconds
                          autoRejoinMaxRetries:
                            type: number
                            description: Auto rejoin max retries
                          pingInterval:
                            type: number
                            description: Ping interval in seconds
                          pingTimeout:
                            type: number
                            description: Ping timeout in seconds
                        required:
                          - host
                          - port
                          - ssl
                        description: IRC connection configuration
                      ident:
                        type: object
                        properties:
                          nick:
                            type: string
                            description: Nick to use on this network
                          username:
                            type: string
                            description: Username
                          gecos:
                            type: string
                            description: GECOS (real name)
                          version:
                            type: string
                            description: Client version (defaults to bot version if not defined)
                          quitMsg:
                            type: string
                            description: Quit message (defaults to bot version if not defined)
                        required:
                          - nick
                          - username
                          - gecos
                        description: IRC Ident information
                      rbac:
                        type: object
                        properties:
                          users:
                            type: object
                            properties: {}
                            description: Users configuration
                        description: RBAC configuration
                      postConnect:
                        type: array
                        items:
                          type: object
                          properties:
                            action:
                              type: string
                              description: Action to perform
                            msg:
                              type: object
                              properties:
                                channel:
                                  type: string
                                  description: Channel or user to send message to
                                msg:
                                  type: string
                                  description: Message content (as string)
                                secretKeyRef:
                                  type: object
                                  properties:
                                    secret:
                                      type: object
                                      properties:
                                        name:
                                          type: string
                                          description: name is unique within a namespace to reference a secret resource.
                                        namespace:
                                          type: string
                                          description: namespace defines the space within which the secret name must be
                                            unique.
                                      description: Reference to k8s secret
                                    key:
                                      type: string
                                      description: Key in the secret to use
                                  required:
                                    - secret
                                    - key
                                  description: Secret key reference for message content
                              description: Message content (as object with channel, msg, and secretKeyRef)
                            join:
                              type: array
                              items:
                                type: object
                                properties:
                                  channel:
                                    type: string
                                    description: Channel name
                                  secretKeyRef:
                                    type: object
                                    properties:
                                      secret:
                                        type: object
                                        properties:
                                          name:
                                            type: string
                                            description: name is unique within a namespace to reference a secret resource.
                                          namespace:
                                            type: string
                                            description: namespace defines the space within which the secret name must be
                                              unique.
                                        description: Reference to k8s secret
                                      key:
                                        type: string
                                        description: Key in the secret to use
                                    required:
                                      - secret
                                      - key
                                    description: Secret key reference for channel join key
                                required:
                                  - channel
                              description: Channels to join
                          required:
                            - action
                        description: Actions to take after connecting to the server
                      broadcastMessages:
                        type: boolean
                        description: Send broadcast events for all received messages
                      commands:
                        type: object
                        properties:
                          commonPrefixRegex:
                            type: string
                            description: Common prefix regex to add to registered command regexes
                        description: Settings related to command modules
                    required:
                      - name
                      - enabled
                      - irc
                      - ident
                  description: List of IRC connections
              required: []
            status:
              type: object
              description: chatconnectionircStatus defines the observed state of
                chatconnectionirc
              properties:
                conditions:
                  type: array
                  description: Conditions describing the current state
                  items:
                    type: object
                    description: Condition contains details for one aspect of the current state of
                      this API Resource.
                    properties: {}
                    required: []
      subresources:
        status: {}
